<?php
declare(strict_types=1);
$pageTitle='Novo produto'; require_once __DIR__.'/includes/header.php';
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM produtos WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch()?:null;$pageTitle='Editar produto';}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)($_POST['id']??0);$nome=trim((string)($_POST['nome'] ?? '')); $preco=(float)str_replace(',','.',(string)($_POST['preco'] ?? '0')); $stock=(int)($_POST['stock']??0); $descricao=trim((string)($_POST['descricao'] ?? '')); if($nome===''){flash('danger','Indica o nome do produto.');}elseif($preco < 0){flash('danger','O preço não pode ser negativo.');}elseif($stock < 0){flash('danger','O stock não pode ser negativo.');}else{if($id){$s=$pdo->prepare('UPDATE produtos SET nome=?,preco=?,stock=?,descricao=? WHERE id=?');$s->execute([$nome,$preco,$stock,$descricao,$id]);flash('success','Produto atualizado.');}else{$s=$pdo->prepare('INSERT INTO produtos(nome,preco,stock,descricao) VALUES(?,?,?,?)');$s->execute([$nome,$preco,$stock,$descricao]);flash('success','Produto criado.');}redirect('produtos.php');}}
?>
<div class="page-intro"><div><span class="section-tag">CATÁLOGO / <?= $edit?'EDITAR':'NOVO' ?></span><p>Preenche os dados e guarda o registo.</p></div><a href="produtos.php" class="btn btn-ghost">Voltar</a></div>
<section class="panel-card form-card"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id'] ?? 0) ?>"><div class="row"><div class="col-md-8 field"><label>Produto</label><input class="form-control app-input" name="nome" value="<?= e($edit['nome']??'') ?>" required></div><div class="col-md-4 field"><label>Preço (€)</label><input class="form-control app-input" name="preco" type="number" step="0.01" min="0" value="<?= e(isset($edit['preco'])?number_format((float)$edit['preco'],2,'.',''):'0.00') ?>" required></div></div><div class="row"><div class="col-md-4 field"><label>Quantidade em stock</label><input class="form-control app-input" name="stock" type="number" min="0" value="<?= (int)($edit['stock']??0) ?>" required></div><div class="col-md-8 field"><label>Descrição</label><input class="form-control app-input" name="descricao" value="<?= e($edit['descricao']??'') ?>"></div></div><div class="form-actions"><a href="produtos.php" class="btn btn-ghost">Cancelar</a><button class="btn btn-primary app-btn">Guardar produto <i class="bi bi-check2"></i></button></div></form></section>
<?php require_once __DIR__.'/includes/footer.php'; ?>
